export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL';

export const SEARCH_MOVIES_START = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';

export const CHANGE_MOVIE_START = 'CHANGE_MOVIE_START';
export const CHANGE_MOVIE_SUCCESS = 'CHANGE_MOVIE_SUCCESS';
export const CHANGE_MOVIE_FAIL = 'CHANGE_MOVIE_FAIL';
export const CHANGE_MOVIE_CANCEL = 'CHANGE_MOVIE_CANCEL';
export const CHANGE_MOVIE_INIT = 'CHANGE_MOVIE_INIT';

export const SELECTED_MOVIE = 'SELECTED_MOVIE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
